# 第九章 测试与调试

​		Python没有编译时静态类型检查。当运行程序时，解释器中没有任何东西能够确保程序正确工作。Python确实支持可选类型注释，可在静态分析中用于检测许多类型的bug(参见第90条)。但是，从根本上讲，它仍然是一种动态语言，任何事情都是可能的。使用Python，最终不知道程序调用的函数是否在运行时定义，即使它们在源代码中明显存在。这种动态行为既是好事也是坏事。

​		大量的Python程序员都说，不进行编译时静态类型检查是值得的，因为这样做的简洁性和简单性可以提高生产率。但是，大多数使用Python的人都至少有一个可怕的情况:程序在运行时遇到愚蠢的错误。我听说过的最糟糕的例子之一是，在生产环境中动态导入(参见第88条)引发SyntaxError，导致服务器进程崩溃。我认识的被这一意外事件击中的程序员已经不再使用Python了。

​		但是我不得不想，为什么在程序部署到生产环境之前，代码没有经过更好的测试?编译时静态类型安全并不是一切。应该始终测试您的代码，无论它是用什么语言编写的。然而，我承认在Python中编写测试来验证正确性可能比在其他语言中更重要。幸运的是，这些会带来风险的动态特性也使得为代码编写测试和调试故障程序变得非常容易。可以使用Python的动态特性和易于重写的行为来实现测试，并确保程序按预期工作。

​		应该将测试视为代码的保险策略。好的测试能确信代码是正确的。如果重构或扩展代码，验证行为(而不是实现)的测试可以很容易地确定更改了什么。这听起来违反直觉，但是有好的测试实际上使修改Python代码更容易，而不是更难。

## 第75条 通过repr字符串输出调试信息

​		当调试Python程序时，print函数和格式化字符串(参见第4条)，或者通过内置的日志模块输出，会很慢。Python内部通常很容易通过普通属性访问(参见第42条)。所需要做的就是调用print来查看程序运行时的状态如何变化，并了解哪里出了问题。

​		print函数输出提供的任何内容的可读字符串版本。例如，打印一个基本字符串只打印字符串的内容，不包含引号:

~~~python
print('foo bar')
>>>
foo bar
~~~

​		这相当于所有这些替代方案:

* 在将值传递给打印之前调用str函数
* 使用'%s'格式字符串和%操作符
* 使用f字符串对值进行默认格式化
* 调用format内置函数
* 显式调用--format--特殊方法
* 显式调用--str--特殊方法

在这里，验证这个行为:

~~~python
my_value = 'foo bar'
print(str(my_value))
print('%s' % my_value)
print(f'{my_value}')
print(format(my_value))
print(my_value.__format__('s'))
print(my_value.__str__())
>>>
foo bar
foo bar
foo bar
foo bar
foo bar
foo bar
~~~

​		问题是，人类可读的值字符串并没有清楚地说明实际的类型及其具体的组合是什么。例如，注意在print的默认输出中，你不能区分数字5和字符串'5'的类型:

~~~python
print(5)
print('5')
int_value = 5
str_value = '5'
print(f'{int_value} == {str_value} ?')
>>>
5
5
5 == 5 ?
~~~

​		如果您正在用print调试一个程序，那么这些类型差异很重要。在调试时，几乎总是希望看到对象的repr版本。repr内置函数返回对象的可打印表示，这应该是它最容易理解的字符串表示。对于大多数内置类型，repr返回的字符串是一个有效的Python表达式:

~~~python
a = '\x07'
print(repr(a))
>>>
'\x07'
~~~

​		将repr的值传递给eval内置函数应该会得到与开始时使用的相同的Python对象(当然，在实践中应该非常小心地使用eval):

~~~python
b = eval(repr(a))
assert a == b
~~~

​		在使用print进行调试时，应该在打印之前对一个值调用repr，以确保类型之间的任何差异都是清楚的：

~~~python
print(repr(5))
print(repr('5'))
>>>
5
'5'
~~~

​		这相当于在%操作符中使用'%r'格式字符串或在!r类型转换中使用fstring:

~~~python
print('%r' % 5)
print('%r' % '5')
int_value = 5
str_value = '5'
print(f'{int_value!r} != {str_value!r}')
>>>
5
'5'
5 != '5'
~~~

​		对于Python类的实例，人类可读的默认字符串值与repr值相同。这意味着传递一个实例给print将会做正确的事情，并且不需要显式地对它调用repr。不幸的是，对象子类的repr的默认实现并不是特别有用。例如，这里定义了一个简单的类，然后打印它的一个实例:

```python
class OpaqueClass:
    def __init__(self, x, y):
        self.x = x
        self.y = y

obj = OpaqueClass(1, 'foo')
print(obj)
>>>
<__main__.OpaqueClass object at 0x10963d6d0>
```

​		这个输出不能传递给eval函数，而且它没有说明对象的实例字段。

​		这个问题有两种解决方案。如果控制了这个类，可以定义你自己的--repr--特殊方法，它返回一个包含重新创建对象的Python表达式的字符串。这里，我为上面的类定义了这个函数:

```python
class BetterClass:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __repr__(self):
        return f'BetterClass({self.x!r}, {self.y!r})'
```

​		现在repr值更有用了:

~~~python
obj = BetterClass(2, 'bar')
print(obj)
>>>
BetterClass(2, 'bar')
~~~

​		当不能控制类定义时，可以进入对象的实例字典，它存储在--dict--属性中。在这里，打印了一个paqueClass实例的内容:

~~~python
obj = OpaqueClass(4, 'baz')
print(obj.__dict__)
>>>
{'x': 4, 'y': 'baz'}
~~~

**要点**

* 在内置Python类型上调用print会生成可读的字符串版本的值，它隐藏了类型信息
* 在内置Python类型上调用repr会生成一个值的可打印字符串版本。这些repr字符串通常可以传递给eval内置函数以获得原始值
* 格式字符串中的%s会产生像str这样的可读字符串。%r会产生像repr这样的可打印字符串。f -字符串生成可用于替换文本表达式的可读字符串，除非您指定!r后缀
* 可以在类上定义--repr--特殊方法来定制实例的可打印表示，并提供更详细的调试信息

## 第76条　在TestCase子类里验证相关的行为

​		在Python中编写测试的规范方法是使用unittest内置模块。例如，假设在utils.py中定义了以下实用函数，我想验证它在各种输入中正确工作:

 *utils.py*

```python
def to_str(data):
    if isinstance(data, str):
        return data
    elif isinstance(data, bytes):
        return data.decode('utf-8')
    else:
        raise TypeError('Must supply str or bytes, '
                        'found: %r' % data)
```

​		为了定义测试，创建了名为test_utils.py或utils_test.py的第二个文件(您更喜欢的命名方案是一种样式选择)，它包含所期望的每个行为的测试:

*utils_test.py*

```python
from unittest import TestCase, main

from example_code.item_76.testing.utils import to_str


class UtilsTestCase(TestCase):
    def test_to_str_bytes(self):
        self.assertEqual('hello', to_str(b'hello'))

    def test_to_str_str(self):
        self.assertEqual('hello', to_str('hello'))

    def test_failing(self):
        self.assertEqual('incorrect', to_str('hello'))

if __name__ == '__main__':
    main()
```

​		然后，使用Python命令行运行测试文件。在这种情况下，两个测试方法通过了，一个失败了，并提供了关于出错原因的有用错误消息:

~~~python
$ python3 utils_test.py
F..
=============================================================
==
FAIL: test_failing (__main__.UtilsTestCase)
-------------------------------------------------------------
--
Traceback (most recent call last):
File "utils_test.py", line 15, in test_failing
self.assertEqual('incorrect', to_str('hello'))
AssertionError: 'incorrect' != 'hello'
- incorrect
+ hello
-------------------------------------------------------------
--
Ran 3 tests in 0.002s
FAILED (failures=1)

~~~

​		测试被组织成TestCase子类。每个测试用例都是一个以单词test开头的方法。如果测试方法运行时没有引发任何类型的Exception(包括来自assert语句的AssertionError)，则认为测试已成功通过。如果一个测试失败，TestCase子类将继续运行其他测试方法，这样您就可以全面了解所有测试是如何进行的，而不是在出现问题的第一个迹象时就停止。如果想快速迭代以修复或改进特定的测试，可以只运行该测试方法，方法是在命令行中指定测试模块中的路径:

~~~python
$ python3 utils_test.py UtilsTestCase.test_to_str_bytes
.
-------------------------------------------------------------
--
Ran 1 test in 0.000s
OK

~~~

​		还可以在特定的断点处直接从测试方法中调用调试器，以便更深入地挖掘失败的原因(参考第80条)。

​		TestCase类提供了在测试中进行断言的辅助方法，例如assertEqual用于验证是否相等，assertTrue用于验证布尔表达式，以及更多(请参阅help(TestCase)以获得完整列表)。它们比内置的断言语句更好，因为它们打印出所有的输入和输出，以帮助理解测试失败的确切原因。例如，这里有一个相同的测试用例，使用和不使用helper断言方法:

*assert_test.py*

```python
from unittest import TestCase, main
from example_code.item_76.testing.utils import to_str

class AssertTestCase(TestCase):
    def test_assert_helper(self):
        expected = 12
        found = 2 * 5
        self.assertEqual(expected, found)

    def test_assert_statement(self):
        expected = 12
        found = 2 * 5
        assert expected == found

if __name__ == '__main__':
    main()
```

​		下面哪个失败消息对您更有帮助?

~~~python
$ python3 assert_test.py
FF
=============================================================
==
FAIL: test_assert_helper (__main__.AssertTestCase)
-------------------------------------------------------------
--
Traceback (most recent call last):
File "assert_test.py", line 16, in test_assert_helper
self.assertEqual(expected, found)
AssertionError: 12 != 10
=============================================================
==
FAIL: test_assert_statement (__main__.AssertTestCase)
-------------------------------------------------------------
--
Traceback (most recent call last):
File "assert_test.py", line 11, in test_assert_statement
assert expected == found
AssertionError
-------------------------------------------------------------
--
Ran 2 tests in 0.001s
FAILED (failures=2)

~~~

​		还有一个assertRaises helper方法用于验证异常，可以作为一个上下文管理器使用在with语句中(参见第66条)。这看起来类似于try/except语句，并且非常清楚异常将在何处被抛出:

```python
from unittest import TestCase, main
from example_code.item_76.testing.utils import to_str


class UtilsErrorTestCase(TestCase):
    def test_to_str_bad(self):
        with self.assertRaises(TypeError):
            to_str(object())

    def test_to_str_bad_encoding(self):
        with self.assertRaises(UnicodeDecodeError):
            to_str(b'\xfa\xfa')

if __name__ == '__main__':
    main()
```

​		可以在TestCase子类中使用复杂的逻辑定义您自己的帮助器方法，以使测试更具可读性。只要确保方法名不以单词test开头，否则它们将像测试用例一样运行。除了调用TestCase断言方法之外，这些自定义测试帮助程序经常使用fail方法来阐明哪些假设或不变条件没有得到满足。例如，在这里定义了一个定制的测试帮助器方法，用于指定生成器的行为：

*helper_test.py*

```python
from unittest import TestCase, main

def sum_squares(values):
    cumulative = 0
    for value in values:
        cumulative += value ** 2
        yield cumulative

class HelperTestCase(TestCase):
    def verify_complex_case(self, values, expected):
        expect_it = iter(expected)
        found_it = iter(sum_squares(values))
        test_it = zip(expect_it, found_it)

        for i, (expect, found) in enumerate(test_it):
            self.assertEqual(
                expect,
                found,
                f'Index {i} is wrong')

        # Verify both generators are exhausted
        try:
            next(expect_it)
        except StopIteration:
            pass
        else:
            self.fail('Expected longer than found')

        try:
            next(found_it)
        except StopIteration:
            pass
        else:
            self.fail('Found longer than expected')

    def test_wrong_lengths(self):
        values = [1.1, 2.2, 3.3]
        expected = [
            1.1**2,
        ]
        self.verify_complex_case(values, expected)

    def test_wrong_results(self):
        values = [1.1, 2.2, 3.3]
        expected = [
            1.1**2,
            1.1**2 + 2.2**2,
            1.1**2 + 2.2**2 + 3.3**2 + 4.4**2,
        ]
        self.verify_complex_case(values, expected)

if __name__ == '__main__':
    main()
```

​		helper方法使测试用例简短易读，输出的错误消息易于理解:

~~~python
$ python3 helper_test.py
FF
=============================================================
==
FAIL: test_wrong_lengths (__main__.HelperTestCase)
-------------------------------------------------------------
--
Traceback (most recent call last):
File "helper_test.py", line 43, in test_wrong_lengths
self.verify_complex_case(values, expected)
File "helper_test.py", line 34, in verify_complex_case
self.fail('Found longer than expected')
AssertionError: Found longer than expected
=============================================================
==
FAIL: test_wrong_results (__main__.HelperTestCase)
-------------------------------------------------------------
--
Traceback (most recent call last):
File "helper_test.py", line 52, in test_wrong_results
self.verify_complex_case(values, expected)
File "helper_test.py", line 24, in verify_complex_case
f'Index {i} is wrong')
AssertionError: 36.3 != 16.939999999999998 : Index 2 is wrong
-------------------------------------------------------------
--
Ran 2 tests in 0.002s
FAILED (failures=2)

~~~

​		通常为每一组相关的测试定义一个TestCase子类。有时，每个函数都有一个TestCase子类，它有许多边界情况。其他时候，TestCase子类跨越了单个模块中的所有函数。我经常创建一个TestCase子类来测试每个基本类及其所有方法。

​		TestCase类还提供了一个subTest帮助器方法，通过在单个测试方法中定义多个测试，可以避免样板文件。这对于编写数据驱动的测试特别有帮助，并且它允许测试方法继续测试其他用例，即使其中一个失败了(类似于TestCase及其包含的测试方法的行为)。显示这个,这里定义了一个数据驱动测试的例子:

*data_driven_test.py*

```python
from unittest import TestCase, main
from example_code.item_76.testing.utils import to_str

class DataDrivenTestCase(TestCase):
    def test_good(self):
        good_cases = [
            (b'my bytes', 'my bytes'),
            ('no error', b'no error'),  # This one will fail
            ('other str', 'other str'),
        ]
        for value, expected in good_cases:
            with self.subTest(value):
                self.assertEqual(expected, to_str(value))

    def test_bad(self):
        bad_cases = [
            (object(), TypeError),
            (b'\xfa\xfa', UnicodeDecodeError),
        ]
        for value, exception in bad_cases:
            with self.subTest(value):
                with self.assertRaises(exception):
                    to_str(value)

if __name__ == '__main__':
    main()
```

​		“没有错误”测试用例失败，打印了一个有用的错误消息，但是所有其他的用例仍然被测试并确认通过:

~~~python
$ python3 data_driven_test.py
.
=============================================================
==
FAIL: test_good (__main__.DataDrivenTestCase) [no error]
-------------------------------------------------------------
--
Traceback (most recent call last):
File "testing/data_driven_test.py", line 18, in test_good
self.assertEqual(expected, to_str(value))
AssertionError: b'no error' != 'no error'
-------------------------------------------------------------
--
Ran 2 tests in 0.001s
FAILED (failures=1)

~~~

*Note*

​		根据项目的复杂性和测试需求，pytest (https://pytest.org)开源包及其大量社区插件可能特别有用。

**要点**

* 可以通过从unittest内置模块创建TestCase类的子类，并为想要测试的每个行为定义一个方法来创建测试。TestCase类上的测试方法必须以单词Test开头。
* 使用TestCase类定义的各种辅助方法(比如assertEqual)来确认测试中的预期行为，而不是使用内置的断言语句
* 考虑使用subTest帮助器方法编写数据驱动测试，以减少样板文件

## 第77条　把测试前、后的准备与清理逻辑写在setUp、tearDown、setUpModule与tearDownModule中，以防用例之间互相干扰

​		TestCase类(参见第76条)通常需要在运行测试方法之前建立测试环境;这有时被称为测试工具。为此，可以覆盖TestCase子类的setUp和tearDown方法。这些方法分别在每个测试方法之前和之后被调用，因此可以确保每个测试独立运行，这是正确测试的一个重要最佳实践。

​		例如，这里定义了一个TestCase，它在每个测试之前创建一个临时目录，并在每个测试完成后删除它的内容:

*environment_test.py*

```python
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest import TestCase, main

class EnvironmentTest(TestCase):
    def setUp(self):
        self.test_dir = TemporaryDirectory()
        self.test_path = Path(self.test_dir.name)

    def tearDown(self):
        self.test_dir.cleanup()

    def test_modify_file(self):
        with open(self.test_path / 'data.bin', 'w') as f:
            f.write('hello')

if __name__ == '__main__':
    main()
```

​		当程序变得复杂时，会想要额外的测试来验证模块之间的端到端交互，而不是只测试独立的代码(使用像mock这样的工具;参见第78项:“使用模拟来测试具有复杂依赖关系的代码”)。这就是单元测试和集成测试之间的区别。在Python中，编写这两种类型的测试非常重要，原因完全相同:除非您证明了这一点，否则您无法保证您的模块能够真正协同工作。

​		一个常见的问题是，为集成测试设置测试环境在计算上可能很昂贵，可能需要大量的时钟时间。例如，可能需要启动一个数据库进程，并等待它完成索引加载，然后才能运行集成测试。这种类型的延迟使得在TestCase类的setUp和tearDown方法中为每个测试做测试准备和清理是不切实际的。

​		为了处理这种情况，unittest模块还支持模块级测试工具初始化。可以一次性配置昂贵的资源，然后在不重复初始化的情况下运行所有TestCase类及其测试方法。稍后，当模块中的所有测试都完成时，可以一次性拆除测试工具。在这里，我通过在包含TestCase类的模块中定义setUpModule和tearDownModule函数来利用这种行为:

*integration_test.py*

```python
from unittest import TestCase, main

def setUpModule():
    print('* Module setup')

def tearDownModule():
    print('* Module clean-up')

class IntegrationTest(TestCase):
    def setUp(self):
        print('* Test setup')

    def tearDown(self):
        print('* Test clean-up')

    def test_end_to_end1(self):
        print('* Test 1')

    def test_end_to_end2(self):
        print('* Test 2')

if __name__ == '__main__':
    main()
```

~~~python
--
Ran 2 tests in 0.000s
OK$ python3 integration_test.py
* Module setup
* Test setup
* Test 1
* Test clean-up
.* Test setup
* Test 2
* Test clean-up
.* Module clean-up
-------------------------------------------------------------
--
Ran 2 tests in 0.000s
OK
~~~

​		可以清楚地看到，setUpModule只由unittest运行一次，并且它发生在任何setUp方法被调用之前。类似地，tearDownModule发生在调用tearDown方法之后。

**要点**

* 同时编写单元测试(针对独立的功能)和集成测试(针对相互交互的模块)是很重要的
* 使用setUp和tearDown方法确保测试彼此隔离，并拥有一个干净的测试环境
* 对于集成测试，使用setUpModule和tearDownModule模块级函数来管理测试模块整个生命周期所需的任何测试工具，以及它包含的所有TestCase类

## 第78条 用Mock来模拟受测代码所依赖的复杂函数

​		编写测试时的另一个常见需求(参见第76条)是，当使用真实的东西太困难或太慢时，使用模拟的函数和类来模拟行为。例如，假设需要一个程序来维持动物园动物的喂食时间表。在这里，定义了一个函数来查询某个物种的所有动物的数据库，并在它们最近一次进食时返回:

```python
class DatabaseConnection:
    def __init__(self, host, port):
        pass

class DatabaseConnectionError(Exception):
    pass

def get_animals(database, species):
    # Query the Database
    raise DatabaseConnectionError('Not connected')
    # Return a list of (name, last_mealtime) tuples
```

​		如何获得用于测试此函数的DatabaseConnection实例?在这里，尝试创建一个，并将它传递到被测试的函数:

```python
try:
    database = DatabaseConnection('localhost', '4444')
    
    get_animals(database, 'Meerkat')
except:
    logging.exception('Expected')
else:
    assert False
```

​		没有数据库在运行，所以这当然会失败。一种解决方案是实际建立一个数据库服务器，并在测试中连接到它。然而，为了只运行一个简单的单元测试，要完全自动化启动数据库、配置其模式、用数据填充它等等，需要做很多工作。此外，设置数据库服务器可能需要大量的时间，这将降低这些单元测试的速度，并使它们更难维护。

​		更好的方法是模拟数据库。mock允许在给定一组预期调用的情况下，为依赖函数提供预期响应。重要的是，不要混淆嘲笑和假冒。伪数据库将提供DatabaseConnection类的大部分行为，但具有更简单的实现，例如基本的内存中、没有持久性的单线程数据库。

​		Python有unittest.mock内置模块，以创建模拟并在测试中使用它们。在这里，定义了一个Mock实例，它模拟了get_animals函数，而没有实际连接到数据库:

```python
from datetime import datetime
from unittest.mock import Mock

mock = Mock(spec=get_animals)
expected = [
    ('Spot', datetime(2019, 6, 5, 11, 15)),
    ('Fluffy', datetime(2019, 6, 5, 12, 30)),
    ('Jojo', datetime(2019, 6, 5, 12, 45)),
]
mock.return_value = expected
```

​		Mock类创建一个模拟函数。mock的return_value属性是调用它时返回的值。spec参数指示mock应该像给定的对象(在本例中是一个函数)一样工作，如果以错误的方式使用，则会出错。

​		例如，在这里,尝试将模拟函数视为一个带有属性的模拟对象:

~~~python
mock.does_not_exist
>>>
Traceback ...
AttributeError: Mock object has no attribute 'does_not_exist'
~~~

​		一旦创建了mock，就可以调用它，获取它的返回值，并验证它返回的内容是否与预期的匹配。使用一个唯一的对象值作为数据库参数，因为它实际上不会被mock用来做任何事情;所关心的是，数据库参数被正确地插入到任何需要DatabaseConnection实例才能工作的依赖函数中(参见第55条):

~~~python
database = object()
result = mock(database, 'Meerkat')
assert result == expected
~~~

​		这将验证模拟是否正确响应，但是如何知道调用模拟的代码是否提供了正确的参数呢?为此，Mock类提供了assert_called_once_with方法，该方法验证是否执行了带有给定参数的单个调用:

~~~python
mock.assert_called_once_with(database, 'Meerkat')
~~~

​		如果提供了错误的参数，就会引发异常，并且任何使用断言的TestCase都会失败:

~~~python
mock.assert_called_once_with(database, 'Giraffe')
>>>
Traceback ...
AssertionError: expected call not found.
Expected: mock(<object object at 0x109038790>, 'Giraffe')
Actual: mock(<object object at 0x109038790>, 'Meerkat')
~~~

​		如我实际上不关心某些单独的参数，比如究竟使用了哪个数据库对象，那么可以通过使用unittest.mock.ANY常量来指示参数的任何值都是可以的。还可以使用Mock的assert_called_with方法来验证对Mock的最近一次调用——在本例中可能有多次调用——符合期望:

~~~python
from unittest.mock import ANY
mock = Mock(spec=get_animals)
mock('database 1', 'Rabbit')
mock('database 2', 'Bison')
mock('database 3', 'Meerkat')
mock.assert_called_with(ANY, 'Meerkat')
~~~

​		当参数不是被测试行为的核心时，ANY在测试中很有用。通过更自由地使用ANY而不是过度指定测试，并且必须通过各种测试参数的期望，在未指定的测试方面犯错误通常是值得的：

~~~python
class MyError(Exception):
	pass
mock = Mock(spec=get_animals)
mock.side_effect = MyError('Whoops! Big problem')
result = mock(database, 'Meerkat')
>>>
Traceback ...
MyError: Whoops! Big problem
~~~

​		还有更多可用的特性，所以一定要查看help(unittest.mock.Mock)以了解所有选项。

​		现在已经展示了Mock如何工作的机制，可以将它应用于实际的测试情况，以展示如何在编写单元测试时有效地使用它。在这里，定义了一个函数在动物园里喂养动物，给出了一组数据库交互函数:

```python
def get_food_period(database, species):
    # Query the Database
    pass
    # Return a time delta

def feed_animal(database, name, when):
    # Write to the Database
    pass

def do_rounds(database, species):
    now = datetime.datetime.utcnow()
    feeding_timedelta = get_food_period(database, species)
    animals = get_animals(database, species)
    fed = 0

    for name, last_mealtime in animals:
        if (now - last_mealtime) > feeding_timedelta:
            feed_animal(database, name, now)
            fed += 1

    return fed
```

​		测试目的是验证当运行do_rounds时，正确的动物被喂食，最新的喂食时间被记录到数据库中，并且函数返回的喂食动物总数与正确的总数相匹配。为了做到这一切，需要模仿datetime。所以测试有一个稳定的时间，不受夏时制和其他短暂变化的影响。需要模拟get_food_period和get_animals，以返回来自数据库的值。需要模拟feed_animal来接受已经写回数据库的数据。

​		问题是:即使知道如何创建这些模拟函数并设置期望，如何使正在测试的do_rounds函数使用模拟依赖函数而不是实际版本?一种方法是把所有东西都作为关键字参数注入(见第25条):

```python
def do_rounds(database, species, *,
              now_func=datetime.utcnow,
              food_func=get_food_period,
              animals_func=get_animals,
              feed_func=feed_animal):
    now = now_func()
    feeding_timedelta = food_func(database, species)
    animals = animals_func(database, species)
    fed = 0

    for name, last_mealtime in animals:
        if (now - last_mealtime) > feeding_timedelta:
            feed_func(database, name, now)
            fed += 1

    return fed
```

​		为了测试这个函数，我需要预先创建所有的Mock实例，并设置它们的期望:

```python
from datetime import timedelta

now_func = Mock(spec=datetime.utcnow)
now_func.return_value = datetime(2019, 6, 5, 15, 45)

food_func = Mock(spec=get_food_period)
food_func.return_value = timedelta(hours=3)

animals_func = Mock(spec=get_animals)
animals_func.return_value = [
    ('Spot', datetime(2019, 6, 5, 11, 15)),
    ('Fluffy', datetime(2019, 6, 5, 12, 30)),
    ('Jojo', datetime(2019, 6, 5, 12, 45)),
]

feed_func = Mock(spec=feed_animal)
```

​		然后，可以通过将mock传递到do_rounds函数来运行测试，以覆盖默认值:

```python
result = do_rounds(
    database,
    'Meerkat',
    now_func=now_func,
    food_func=food_func,
    animals_func=animals_func,
    feed_func=feed_func)

assert result == 2
```

​		最后，可以验证所有对依赖函数的调用都符期望:

```python
from unittest.mock import call

food_func.assert_called_once_with(database, 'Meerkat')

animals_func.assert_called_once_with(database, 'Meerkat')

feed_func.assert_has_calls(
    [
        call(database, 'Spot', now_func.return_value),
        call(database, 'Fluffy', now_func.return_value),
    ],
    any_order=True)
```

​		不验证datetime.Utcnowd的参数或者它被调用了多少次因为这是由函数的返回值间接验证的。对于get_food_period和get_animals，使用assert_called_once_with来验证使用指定参数的单个调用。对于feed_animal函数，使用unittest.mock.call助手和assert_has_calls方法验证两次调用——它们的顺序无关紧要——并将其写入数据库。

​		这种使用仅关键字参数来注入模拟的方法可以工作，但它相当冗长，需要更改希望测试的每个函数。unittest.mock.patch系列函数使注入模拟更容易。它临时重新分配模块或类的属性，例如我在上面定义的数据库访问函数。例如，这里我使用patch覆盖get_animals作为mock:

```python
from unittest.mock import patch

print('Outside patch:', get_animals)

with patch('__main__.get_animals'):
    print('Inside patch: ', get_animals)

print('Outside again:', get_animals)
>>>
Outside patch: <function get_animals at 0x109217040>
Inside patch: <MagicMock name='get_animals' id='4454622832'>
Outside again: <function get_animals at 0x109217040>
```

​		Patch适用于许多模块、类和属性。它可以用于语句(参见第66条),作为装饰函数(参见第26条),或在setUp和tearDown TestCase类的方法(参见第76条)。有关完整的选项，请参阅help(unittest.mock.patch)。

​		然而，补丁并不是在所有情况下都有效。例如，为了测试do_rounds，要模拟出datetime.utcnow类方法返回的当前时间。Python不允许这样做，因为datetime类是在c扩展模块中定义的，不能以这种方式修改:

~~~python
fake_now = datetime(2019, 6, 5, 15, 45)
with patch('datetime.datetime.utcnow'):
	datetime.utcnow.return_value = fake_now
>>>
Traceback ...
TypeError: can't set attributes of built-in/extension type
➥'datetime.datetime'

~~~

​		为了解决这个问题，可以创建另一个helper函数来获取可以被修补的时间:

```python
def get_do_rounds_time():
    return datetime.datetime.utcnow()

def do_rounds(database, species):
    now = get_do_rounds_time()

with patch('__main__.get_do_rounds_time'):
    pass
```

​		或者，也可以为datetime.Utcnow使用一个只使用关键字的参数或使用补丁的所有其他模拟:

```python
def do_rounds(database, species, *, utcnow=datetime.utcnow):
    now = utcnow()
    feeding_timedelta = get_food_period(database, species)
    animals = get_animals(database, species)
    fed = 0

    for name, last_mealtime in animals:
        if (now - last_mealtime) > feeding_timedelta:
            feed_animal(database, name, now)
            fed += 1

    return fed
```

​		将采用后一种方法。现在，可以用贴片了。多个功能来创建许多模拟和设置它们的期望:

```python
from unittest.mock import DEFAULT

with patch.multiple('__main__',
                    autospec=True,
                    get_food_period=DEFAULT,
                    get_animals=DEFAULT,
                    feed_animal=DEFAULT):
    now_func = Mock(spec=datetime.utcnow)
    now_func.return_value = datetime(2019, 6, 5, 15, 45)
    get_food_period.return_value = timedelta(hours=3)
    get_animals.return_value = [
        ('Spot', datetime(2019, 6, 5, 11, 15)),
        ('Fluffy', datetime(2019, 6, 5, 12, 30)),
        ('Jojo', datetime(2019, 6, 5, 12, 45))
    ]
```

​		安装就绪后，可以运行测试并验证使用patch.multiple的With语句中的调用是正确的:

```python
result = do_rounds(database, 'Meerkat', utcnow=now_func)
assert result == 2

get_food_period.assert_called_once_with(database, 'Meerkat')
get_animals.assert_called_once_with(database, 'Meerkat')
feed_animal.assert_has_calls(
    [
        call(database, 'Spot', now_func.return_value),
        call(database, 'Fluffy', now_func.return_value),
    ],
    any_order=True)
```

​		patch的关键字参数多个对应于想要重写的--main--模块中的名称。DEFAULT值表示希望为每个名称创建一个标准Mock实例。由于autospec=True参数，所有生成的模拟都将遵循它们要模拟的对象的规范。

​		这些模拟如预期的那样工作，但重要的是要认识到，通过重构代码使其更具可测试性，可以进一步提高这些测试的可读性，并减少样板文件(参见第79条)。

**要点**

* unittest.mock模块提供了一种使用mock类模拟接口行为的方法。当很难设置被测试代码所需要的依赖项时，模拟在测试中非常有用
* 在使用Mock时，必须使用Mock验证所测试代码的行为以及代码调用依赖函数的方式。Assert_called_once_with方法族
* 关键字参数和unittest.mock.patch系列函数可以用来将模拟注入到被测试的代码中

## 第79条　把受测代码所依赖的系统封装起来，以便于模拟和测试

​		在前一项中(参见第78条:“使用mock测试复杂依赖项的代码”)，演示了如何使用unittest.mock内置模块——包括mock类和函数的补丁系列——以编写具有复杂依赖关系的测试，如数据库。然而，生成的测试代码需要许多样板文件，这可能使代码的新读者更难理解测试试图验证什么。

​		改进这些测试的一种方法是使用包装器对象封装数据库接口，而不是将DatabaseConnection对象作为参数传递给函数。重构代码(见第89项:“考虑对一种方法的重构和迁移使用的警告”)来使用更好的抽象通常是值得的，因为它有助于创建模拟和编写测试。在这里，将前一项中的各种数据库助手函数重新定义为类上的方法，而不是独立的函数:

```python
class ZooDatabase:

    def get_animals(self, species):
        pass

    def get_food_period(self, species):
        pass

    def feed_animal(self, name, when):
        pass
```

​		现在，可以重新定义do_rounds函数来调用ZooDatabase对象上的方法:

```python
from datetime import datetime

def do_rounds(database, species, *, utcnow=datetime.utcnow):
    now = utcnow()
    feeding_timedelta = database.get_food_period(species)
    animals = database.get_animals(species)
    fed = 0

    for name, last_mealtime in animals:
        if (now - last_mealtime) >= feeding_timedelta:
            database.feed_animal(name, now)
            fed += 1

    return fed
```

​		为do_rounds编写测试现在简单多了，因为不再需要使用unittest.mock.patch将模拟注入到被测试的代码中。相反，可以创建一个Mock实例来表示ZooDatabase，并将其作为数据库参数传入。Mock类为所访问的任何属性名返回一个模拟对象。这些属性可以像调用方法一样调用，然后可以使用这些方法来设置期望和验证调用。这使得模拟一个类的所有方法变得很容易:

```python
from unittest.mock import Mock

database = Mock(spec=ZooDatabase)
print(database.feed_animal)
database.feed_animal()
database.feed_animal.assert_any_call()
```

​		可以通过使用ZooDatabase封装重写Mock设置代码:

```python
from datetime import timedelta
from unittest.mock import call

now_func = Mock(spec=datetime.utcnow)
now_func.return_value = datetime(2019, 6, 5, 15, 45)

database = Mock(spec=ZooDatabase)
database.get_food_period.return_value = timedelta(hours=3)
database.get_animals.return_value = [
    ('Spot', datetime(2019, 6, 5, 11, 15)),
    ('Fluffy', datetime(2019, 6, 5, 12, 30)),
    ('Jojo', datetime(2019, 6, 5, 12, 55))
]
```

​		然后可以运行正在测试的函数，并验证所有依赖的方法都按预期被调用:

```python
result = do_rounds(database, 'Meerkat', utcnow=now_func)
assert result == 2

database.get_food_period.assert_called_once_with('Meerkat')
database.get_animals.assert_called_once_with('Meerkat')
database.feed_animal.assert_has_calls(
    [
        call('Spot', now_func.return_value),
        call('Fluffy', now_func.return_value),
    ],
    any_order=True)
```

​		在模拟类时使用spec参数Mock特别有用，因为它可以确保被测试的代码不会意外调用拼写错误的方法名。这可以让你避免一个常见的陷阱，即相同的错误出现在代码和单元测试中，掩盖了一个真正的错误，而这个错误稍后会在生产中暴露出来:

```python
database.bad_method_name()
>>>
Traceback ...
AttributeError: Mock object has no attribute
'bad_method_name'

```

​		如果想用一个中级集成测试端到端地测试这个程序(参见第77项:“使用setUp、tearDown、setUpModule和tearDownModule隔离彼此的测试”)，仍然需要一种方法将一个模拟的ZooDatabase注入到程序中。可以通过创建一个helper函数来实现这一点，该函数充当依赖注入的接缝。在这里，定义了这样一个helper函数，它通过使用全局语句来缓存模块范围内的ZooDatabase(见第86项:“考虑模块范围内的代码来配置部署环境”):

```python
DATABASE = None

def get_database():
    global DATABASE
    if DATABASE is None:
        DATABASE = ZooDatabase()
    return DATABASE

def main(argv):
    database = get_database()
    species = argv[1]
    count = do_rounds(database, species)
    print(f'Fed {count} {species}(s)')
    return 0
```

​		现在，可以使用patch注入模拟的ZooDatabase，运行测试，并验证程序的输出。没有使用模拟的datetime.utcnow;相反，依赖于模拟返回的数据库记录来相对于当前时间，以便产生与单元测试类似的行为。这种方法比模拟所有东西更古怪，但它也测试了更多的表面区域:

```python
import contextlib
import io
from unittest.mock import patch

with patch('__main__.DATABASE', spec=ZooDatabase):
    now = datetime.utcnow()

    DATABASE.get_food_period.return_value = timedelta(hours=3)
    DATABASE.get_animals.return_value = [
        ('Spot', now - timedelta(minutes=4.5)),
        ('Fluffy', now - timedelta(hours=3.25)),
        ('Jojo', now - timedelta(hours=3)),
    ]

    fake_stdout = io.StringIO()
    with contextlib.redirect_stdout(fake_stdout):
        main(['program name', 'Meerkat'])

    found = fake_stdout.getvalue()
    expected = 'Fed 2 Meerkat(s)\n'

    assert found == expected
```

​		结果符合期望。创建这个集成测试很简单，因为我设计的实现使它更容易测试。

**要点**

* 当单元测试需要大量重复的样板文件来设置模拟时，一种解决方案可能是将依赖项的功能封装到更容易模拟的类中
* unittest.mock内置模块的Mock类通过为所访问的每个属性返回一个新的Mock来模拟类，该Mock可以作为模拟方法
* 对于端到端测试，重构代码以获得更多的帮助函数是很有价值的，这些帮助函数可以充当显式接缝，用于在测试中注入模拟依赖项

## 第80条　考虑用pdb做交互调试

​		在开发程序时，每个人都会在代码中遇到bug。使用print函数可以帮助跟踪许多问题的来源(参见第75项:“使用repr字符串调试输出”)。为导致问题的特定用例编写测试是另一种隔离问题的好方法(参见第76项:“在TestCase子类中验证相关行为”)。

​		但是这些工具还不足以找到所有的根本原因。当需要更强大的工具时，可以尝试一下Python内置的交互式调试器。调试器允许检查程序状态，打印局部变量，并在Python程序中一步一步地执行一条语句。

​		在大多数其他编程语言中，可以通过指定希望在源文件的哪一行上停止来使用调试器，然后执行程序。相反，在Python中，使用调试器的最简单方法是修改程序，在认为有值得研究的问题之前直接启动调试器。这意味着为了运行调试器而启动一个Python程序和正常启动它之间没有区别。

​		要初始化调试器，只需调用breakpoint内置函数。这相当于导入pdb内置模块并运行它的set_trace函数:

*always_breakpoint.py*

```python
import math

def compute_rmse(observed, ideal):
    total_err_2 = 0
    count = 0
    for got, wanted in zip(observed, ideal):
        err_2 = (got - wanted) ** 2
        breakpoint()  # Start the debugger here
        total_err_2 += err_2
        count += 1

    mean_err = total_err_2 / count
    rmse = math.sqrt(mean_err)
    return rmse

result = compute_rmse(
    [1.8, 1.7, 3.2, 6],
    [2, 1.5, 3, 5])
print(result)
```

​		一旦断点函数运行，程序就会在断点调用后紧接着的代码行之前暂停执行。启动程序的终端变成了一个交互式的Python shell:

~~~sh
$ python3 always_breakpoint.py
> always_breakpoint.py(12)compute_rmse()
-> total_err_2 += err_2
(Pdb)
~~~

​		在(Pdb)提示符中，可以输入局部变量的名称，以查看输出它们的值(或使用p &lt;name&gt;)。通过调用locals内置函数，可以看到所有局部变量的列表。可以导入模块、检查全局状态、构造新对象、运行内置的help函数，甚至修改正在运行的程序的某些部分—需要做的一切以帮助进行调试。

​		此外，调试器有各种特殊的命令来控制和理解程序的执行;键入help以查看完整列表。

​		三个非常有用的命令使检查正在运行的程序更加容易:

* where:打印当前执行调用堆栈。这可以让确定在程序中的位置以及如何到达断点触发器
* up：将范围从执行调用堆栈向上移动到当前函数的调用者。这允许在导致断点的程序的更高级别中检查局部变量
* down：将范围向下移动到执行调用堆栈一层

​	当检查完当前状态，可以使用这5个调试器命令以不同的方式控制程序的执行:

* step：运行程序直到程序中的下一行执行，然后将控制返回到调试器提示符。如果执行的下一行包括调用一个函数，则调试器将在被调用的函数内停止
* next：运行该程序，直到当前函数中的下一行执行，然后将控制权返回给调试器提示符。如果执行的下一行包含调用函数，则调试器在被调用函数返回之前不会停止
* return：运行程序直到当前函数返回，然后将控制返回给调试器提示符
* continue：继续运行程序，直到命中下一个断点(通过断点调用或由调试器命令添加的断点)
* quit：退出调试器并结束程序。如果您发现了问题、做得太过了或需要进行程序修改并再次尝试，请运行此命令

​		断点函数可以在程序的任何地方调用。如果知道试图调试的问题只在特殊情况下发生，那么可以编写普通的旧Python代码，在满足特定条件后调用breakpoint。例如，这里只有在数据点的平方错误大于1时才启动调试器:

*conditional_breakpoint.py*

```python
import math
def compute_rmse(observed, ideal):
    total_err_2 = 0
    count = 0
    for got, wanted in zip(observed, ideal):
        err_2 = (got - wanted) ** 2
        if err_2 >= 1:  # Start the debugger if True
            breakpoint()
        total_err_2 += err_2
        count += 1
    mean_err = total_err_2 / count
    rmse = math.sqrt(mean_err)
    return rmse

result = compute_rmse(
    [1.8, 1.7, 3.2, 7],
    [2, 1.5, 3, 5])
print(result)
```

​		当运行程序并进入调试器时，可以通过检查局部变量来确认条件为真:

~~~sh
$ python3 conditional_breakpoint.py
> conditional_breakpoint.py(14)compute_rmse()
-> total_err_2 += err_2
(Pdb) wanted
5
(Pdb) got
7
(Pdb) err_2
4
~~~

​		到达调试器提示的另一种有用方法是使用事后调试。这使能够在程序已经引发异常并崩溃后调试它。当不太确定将断点函数调用放置在何处时，这尤其有用。

​		这里，有一个脚本，将崩溃由于7j复数出现在函数的参数之一:

*postmortem_breakpoint.py*

```python
import math

def compute_rmse(observed, ideal):
    total_err_2 = 0
    count = 0
    for got, wanted in zip(observed, ideal):
        err_2 = (got - wanted) ** 2
        total_err_2 += err_2
        count += 1

    mean_err = total_err_2 / count
    rmse = math.sqrt(mean_err)
    return rmse

result = compute_rmse(
    [1.8, 1.7, 3.2, 7j],  # Bad input
    [2, 1.5, 3, 5])
print(result)
```

​		使用python3 -m pdb -c continue &lt;程序路径&gt;在PDB模块的控制下运行程序。continue命令告诉pdb立即启动程序。一旦它运行，程序碰到一个问题，并自动进入交互式调试器，此时可以检查程序状态

~~~sh
$ python3 -m pdb -c continue postmortem_breakpoint.py
Traceback (most recent call last):
File ".../pdb.py", line 1697, in main
pdb._runscript(mainpyfile)
File ".../pdb.py", line 1566, in _runscript
self.run(statement)
File ".../bdb.py", line 585, in run
exec(cmd, globals, locals)
File "<string>", line 1, in <module>
File "postmortem_breakpoint.py", line 4, in <module>
import math
File "postmortem_breakpoint.py", line 16, in compute_rmse
rmse = math.sqrt(mean_err)
TypeError: can't convert complex to float
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> postmortem_breakpoint.py(16)compute_rmse()
-> rmse = math.sqrt(mean_err)
(Pdb) mean_err
(-5.97-17.5j)
~~~

​		在交互式Python解释器中遇到未捕获的异常后，也可以通过调用pdb模块的pm函数来使用事后调试(通常用一行代码导入pdb;pdb.pm ()):

~~~sh
$ python3
>>> import my_module
>>> my_module.compute_stddev([5])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "my_module.py", line 17, in compute_stddev
variance = compute_variance(data)
File "my_module.py", line 13, in compute_variance
variance = err_2_sum / (len(data) - 1)
ZeroDivisionError: float division by zero
>>> import pdb; pdb.pm()
> my_module.py(13)compute_variance()
-> variance = err_2_sum / (len(data) - 1)
(Pdb) err_2_sum
0.0
(Pdb) len(data)
1
~~~

**要点**

* 通过调用断点内置函数，可以在程序中感兴趣的点直接初始化Python交互式调试器
* Python调试器提示符是一个完整的Python shell，它允许检查和修改正在运行的程序的状态
* PDB shell命令让精确地控制程序的执行，并允许在检查程序状态和进度程序执行之间进行切换
* pdb模块可用于在独立Python程序中发生异常(使用Python -m pdb -c continue &lt;程序路径&gt;)或交互式Python解释器(使用import pdb;pdb.pm())

